version: '3.8'
services:
  offaxis:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./dist/:/usr/share/nginx/html:ro # Serve the first static website from this directory
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '5173:80' # Expose port 80 within Docker network