version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - app-network

  backend:
    image: node:20-alpine3.21
    container_name: node-app
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - "5001:5001"
    command: >
      sh -c "npm install --only="development" && npm run start:prod"
    environment:
      - NODE_ENV=production
      - DB_USERNAME=root
      - DB_PASSWORD=example
      - DB_HOSTNAME=mysql
      - DB_DATABASENAME=mydb
      - DB_PORT=3306
      - JWT_SECRET_KEY=test
      - CLIENT_URL=https://off-axis.sirapop.dev
    healthcheck:
      test: ["CMD", "sh", "-c", "mysqladmin ping -h mysql -u root -pexample --silent"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge